[package]
name = "ffphotojoin"
description = "A simple photo-joining library for Rust"
version = "0.1.0"
authors = ["CJ Burkey <cjburkey01@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
image = "0.23.12"
thiserror = "1.0.23"